import 'package:flutter/material.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanverifikasinomerteleponwidget/generated/GeneratedDidntReceiveSMSWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanverifikasinomerteleponwidget/generated/GeneratedTabBarWidget5.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanverifikasinomerteleponwidget/generated/GeneratedVector4Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanverifikasinomerteleponwidget/generated/GeneratedSendagainWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanverifikasinomerteleponwidget/generated/GeneratedStatusbarWidget5.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanverifikasinomerteleponwidget/generated/GeneratedEnterTheCodeweSentTo6285452515923Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanverifikasinomerteleponwidget/generated/GeneratedLanjutWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanverifikasinomerteleponwidget/generated/Generated0354Widget.dart';

/* Frame Halaman Verifikasi Nomer Telepon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanVerifikasiNomerTeleponWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 24.0,
                child: GeneratedStatusbarWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 35.0,
                child: GeneratedTabBarWidget5(),
              ),
              Positioned(
                left: 26.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 96.0,
                child: GeneratedEnterTheCodeweSentTo6285452515923Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 210.5,
                height: 0.0,
                child: GeneratedVector4Widget(),
              ),
              Positioned(
                left: 98.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 29.0,
                child: Generated0354Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 26.0,
                child: GeneratedDidntReceiveSMSWidget(),
              ),
              Positioned(
                left: 262.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 26.0,
                child: GeneratedSendagainWidget(),
              ),
              Positioned(
                left: 336.0,
                top: 628.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 60.0,
                child: GeneratedLanjutWidget(),
              )
            ]),
      ),
    ));
  }
}
