import 'package:flutter/material.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedInfoWidget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedAccountWidget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedJakeWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedAccountWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedStatusbarWidget2.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedTabBarWidget2.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedBioTujuanhidupkitaadalahmenjadibahagiaWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedAppBarWidget2.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedOnlineWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanprofilewidget/generated/GeneratedCallWidget4.dart';

/* Frame Halaman Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 224, 222, 222),
                ),
              ),
              Positioned(
                left: -3.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 35.0,
                child: GeneratedTabBarWidget2(),
              ),
              Positioned(
                left: 46.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 32.0,
                child: GeneratedAccountWidget(),
              ),
              Positioned(
                left: 170.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 32.0,
                child: GeneratedOnlineWidget(),
              ),
              Positioned(
                left: 155.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 32.0,
                child: GeneratedJakeWidget(),
              ),
              Positioned(
                left: 125.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 163.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 52.0,
                child: GeneratedAppBarWidget2(),
              ),
              Positioned(
                left: 7.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 404.0,
                height: 24.0,
                child: GeneratedStatusbarWidget2(),
              ),
              Positioned(
                left: 46.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 82.0,
                child: GeneratedBioTujuanhidupkitaadalahmenjadibahagiaWidget(),
              ),
              Positioned(
                left: 46.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 408.0,
                height: 47.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 246.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 44.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 3.0,
                top: 499.9998779296875,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedCallWidget4(),
              ),
              Positioned(
                left: 3.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedInfoWidget1(),
              ),
              Positioned(
                left: -3.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 45.0,
                child: GeneratedAccountWidget1(),
              )
            ]),
      ),
    ));
  }
}
