import 'package:flutter/material.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedTabBarWidget4.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedFloatingActionButtonWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedLine7Widget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedGroup1Widget3.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedGroup5Widget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedToolbarWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedGroup2Widget2.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedStatusbarWidget4.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanutamawidget/generated/GeneratedLine1Widget.dart';

/* Frame Halaman Utama
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanUtamaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 224, 222, 222),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 80.0,
                child: GeneratedToolbarWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 24.0,
                child: GeneratedStatusbarWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 35.0,
                child: GeneratedTabBarWidget4(),
              ),
              Positioned(
                left: 355.0,
                top: 609.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 57.9334716796875,
                child: GeneratedFloatingActionButtonWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 57.0,
                child: GeneratedGroup5Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 73.0,
                child: GeneratedGroup4Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 54.0,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 54.0,
                child: GeneratedGroup2Widget2(),
              ),
              Positioned(
                left: 26.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 54.0,
                child: GeneratedGroup1Widget3(),
              ),
              Positioned(
                left: 36.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 333.0014953613281,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 333.0014953613281,
                height: 1.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 501.968017578125,
                right: null,
                bottom: null,
                width: 333.0014953613281,
                height: 1.0,
                child: GeneratedLine7Widget1(),
              ),
              Positioned(
                left: 36.00008773803711,
                top: 283.97161865234375,
                right: null,
                bottom: null,
                width: 333.0014953613281,
                height: 1.0,
                child: GeneratedLine5Widget1(),
              )
            ]),
      ),
    ));
  }
}
