import 'package:flutter/material.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedHelpWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedNotificationWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedStatusbarWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedPrivacyAndSecurityWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedAppBarWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedLockWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedInfoWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedDataStorageWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedNotificationsWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedTabBarWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamansettingwidget/generated/GeneratedStorageWidget.dart';

/* Frame Halaman Setting
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanSettingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 224, 222, 222),
                ),
              ),
              Positioned(
                left: -3.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 35.0,
                child: GeneratedTabBarWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 52.0,
                child: GeneratedAppBarWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 404.0,
                height: 24.0,
                child: GeneratedStatusbarWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 26.0,
                child: GeneratedPrivacyAndSecurityWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 29.0,
                child: GeneratedNotificationsWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 26.0,
                child: GeneratedDataStorageWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 28.0,
                child: GeneratedLockWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 28.0,
                child: GeneratedNotificationWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 28.0,
                child: GeneratedStorageWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 28.0,
                child: GeneratedInfoWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 29.0,
                child: GeneratedHelpWidget(),
              )
            ]),
      ),
    ));
  }
}
