import 'package:flutter/material.dart';
import 'package:flutterapp/halotalkapp/generatedmenuoverlaywidget/generated/GeneratedCallWidget5.dart';
import 'package:flutterapp/halotalkapp/generatedmenuoverlaywidget/generated/GeneratedInviteFriendsWidget.dart';
import 'package:flutterapp/halotalkapp/generatedmenuoverlaywidget/generated/GeneratedProfileWidget.dart';
import 'package:flutterapp/halotalkapp/generatedmenuoverlaywidget/generated/GeneratedSettingWidget.dart';
import 'package:flutterapp/halotalkapp/generatedmenuoverlaywidget/generated/GeneratedNewGroupWidget.dart';

/* Frame Menu Overlay
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuOverlayWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 295.0,
        height: 198.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 7.0,
                top: 4.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 45.0,
                child: GeneratedNewGroupWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 29.0,
                child: GeneratedCallWidget5(),
              ),
              Positioned(
                left: 7.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 40.0,
                child: GeneratedInviteFriendsWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 22.0,
                child: GeneratedProfileWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 17.0,
                child: GeneratedSettingWidget(),
              )
            ]),
      ),
    ));
  }
}
