import 'package:flutter/material.dart';
import 'package:flutterapp/halotalkapp/generatedmemulaiwidget/generated/GeneratedPaperPlaneMessagesWidget.dart';
import 'package:flutterapp/halotalkapp/generatedmemulaiwidget/generated/GeneratedCharacter3Widget.dart';
import 'package:flutterapp/halotalkapp/generatedmemulaiwidget/generated/GeneratedSkipDotWidget.dart';
import 'package:flutterapp/halotalkapp/generatedmemulaiwidget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/halotalkapp/generatedmemulaiwidget/generated/GeneratedBgcircleWidget.dart';
import 'package:flutterapp/halotalkapp/generatedmemulaiwidget/generated/GeneratedTabBarWidget9.dart';

/* Frame Memulai
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMemulaiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 39, 146, 246),
                ),
              ),
              Positioned(
                left: -28.0,
                top: -128.0,
                right: null,
                bottom: null,
                width: 469.0,
                height: 471.0,
                child: GeneratedBgcircleWidget(),
              ),
              Positioned(
                left: 87.00012969970703,
                top: 147.0,
                right: null,
                bottom: null,
                width: 260.50286865234375,
                height: 270.947509765625,
                child: GeneratedCharacter3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 20.0,
                child: GeneratedSkipDotWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 106.0,
                child: GeneratedLogoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 35.0,
                child: GeneratedTabBarWidget9(),
              ),
              Positioned(
                left: 150.51771545410156,
                top: 468.51739501953125,
                right: null,
                bottom: null,
                width: 52.0,
                height: 51.0,
                child: GeneratedPaperPlaneMessagesWidget(),
              )
            ]),
      ),
    ));
  }
}
