import 'package:flutter/material.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedTabBarWidget3.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedAppBarWidget3.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedPhoto151924222083109410926fbff1Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedGroup1Widget2.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedStatusbarWidget3.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedVector2Widget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanchatwidget/generated/GeneratedGroup3Widget.dart';

/* Frame Halaman Chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanChatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -205.0,
                top: -305.0,
                right: null,
                bottom: null,
                width: 629.0,
                height: 1049.0,
                child: GeneratedPhoto151924222083109410926fbff1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 35.0,
                child: GeneratedTabBarWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 61.0,
                child: GeneratedAppBarWidget3(),
              ),
              Positioned(
                left: 14.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 41.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 41.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 41.0,
                child: GeneratedGroup2Widget1(),
              ),
              Positioned(
                left: 198.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 27.0,
                child: GeneratedGroup1Widget2(),
              ),
              Positioned(
                left: 383.086669921875,
                top: 115.0,
                right: null,
                bottom: null,
                width: 16.1315860748291,
                height: 11.1875,
                child: GeneratedVector1Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 106.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 24.0,
                child: GeneratedStatusbarWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 630.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 66.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 87.64373779296875,
                top: 241.73390197753906,
                right: null,
                bottom: null,
                width: 16.1315860748291,
                height: 11.1875,
                child: GeneratedVector2Widget1(),
              )
            ]),
      ),
    ));
  }
}
