import 'package:flutter/material.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanloginwidget/generated/GeneratedNextWidget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanloginwidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanloginwidget/generated/GeneratedStatusbarWidget6.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanloginwidget/generated/Generated85452515923Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanloginwidget/generated/GeneratedEnteryourphonenumbertogetstartedYouwillreceiveaverifica.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanloginwidget/generated/Generated62Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanloginwidget/generated/GeneratedNegaraWidget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanloginwidget/generated/GeneratedTabBarWidget7.dart';

/* Frame Halaman Log in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 3.0,
                right: null,
                bottom: null,
                width: 410.0,
                height: 24.0,
                child: GeneratedStatusbarWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 35.0,
                child: GeneratedTabBarWidget7(),
              ),
              Positioned(
                left: 26.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 124.0,
                child:
                    GeneratedEnteryourphonenumbertogetstartedYouwillreceiveaverifica(),
              ),
              Positioned(
                left: 26.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 354.0,
                height: 67.0,
                child: GeneratedNegaraWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 65.0,
                child: Generated62Widget(),
              ),
              Positioned(
                left: 117.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 65.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 128.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 45.0,
                child: Generated85452515923Widget(),
              ),
              Positioned(
                left: 336.0,
                top: 628.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 60.0,
                child: GeneratedNextWidget1(),
              )
            ]),
      ),
    ));
  }
}
