import 'package:flutter/material.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedTabBarWidget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedCallWidget3.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedStatusbarWidget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedAppBarWidget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedCallWidget1.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedCallWidget2.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/halotalkapp/generatedhalamanteleponwidget/generated/GeneratedGroup8Widget.dart';

/* Frame Halaman Telepon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanTeleponWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 224, 222, 222),
                ),
              ),
              Positioned(
                left: -3.0,
                top: 696.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 35.0,
                child: GeneratedTabBarWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 52.0,
                child: GeneratedAppBarWidget1(),
              ),
              Positioned(
                left: 7.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 404.0,
                height: 24.0,
                child: GeneratedStatusbarWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 54.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 57.0,
                child: GeneratedGroup5Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 54.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 332.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 60.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 1.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 1.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 335.0,
                top: 173.47540283203125,
                right: null,
                bottom: null,
                width: 36.47999954223633,
                height: 32.95000076293945,
                child: GeneratedCallWidget1(),
              ),
              Positioned(
                left: 336.0,
                top: 279.4771728515625,
                right: null,
                bottom: null,
                width: 36.48176193237305,
                height: 32.94832229614258,
                child: GeneratedCallWidget2(),
              ),
              Positioned(
                left: 335.0,
                top: 384.4771728515625,
                right: null,
                bottom: null,
                width: 36.48176193237305,
                height: 32.94832229614258,
                child: GeneratedCallWidget3(),
              )
            ]),
      ),
    ));
  }
}
